#!/bin/sh

# $1 contains a path to the file containing the commit message.

if [[ $(grep -c -E "^SPLEVO-[0-9]+[[:space:]].*$" $1) -gt 0 ]];
then
	exit 0
else
	echo "The commit message does not start with the issue id. Please use"
	echo "SPLEVO-XXXX Your message"
	exit 1
fi