<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="vrm" nsURI="http://splevo.org/vrm/1.0" nsPrefix="org.splevo.vrm">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="Variability Realization Model to describe available realization techniques and configure how to realize the variation points of a variation point model (VPM)."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="VariabilityRealizationTechnique">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A specific technique for realizing the variability of a variation point."/>
    </eAnnotations>
    <eOperations name="canBeAppliedTo" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="variationPoint" eType="ecore:EClass ../../org.splevo.vpm/model/vpm.ecore#//variability/VariationPoint"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The name of the technique."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariabilityRealizationConfiguration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variationPoint" eType="ecore:EClass ../../org.splevo.vpm/model/vpm.ecore#//variability/VariationPoint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="technique" eType="#//VariabilityRealizationTechnique"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariabilityRealizationModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="RealizationConfigurations"
        upperBound="-1" eType="#//VariabilityRealizationConfiguration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vpm" lowerBound="1" eType="ecore:EClass ../../org.splevo.vpm/model/vpm.ecore#//variability/VariationPointModel"/>
  </eClassifiers>
</ecore:EPackage>
