<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="vrm" nsURI="http://splevo.org/vrm/1.0" nsPrefix="org.splevo.vrm">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="Variability Realization Model to describe available realization techniques and configure how to realize the variation points of a variation point model (VPM)."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="VariabilityRealizationTechnique">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A specific technique for realizing the variability of a variation point.&#xD;&#xA;Techniques should be on the real implementation level and not on a generic conceptual one.&#xD;&#xA;The must be realizable."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="refactoringId" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The internal id of the refactoring implementation providing this technique and able to refactor the copies."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The human readable name of the technique."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A description to understand the technique and it's implications."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="supportedBindingTimes"
        lowerBound="1" upperBound="-1" eType="ecore:EEnum ../../org.splevo.vpm/model/vpm.ecore#//variability/BindingTime">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The binding times supported by this technique"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="supportedExtendibility"
        lowerBound="1" upperBound="-1" eType="ecore:EEnum ../../org.splevo.vpm/model/vpm.ecore#//variability/Extendibility">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The extendibility options supported by this technique."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="supportedVariabilityTypes"
        lowerBound="1" upperBound="-1" eType="ecore:EEnum ../../org.splevo.vpm/model/vpm.ecore#//variability/VariabilityType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The variability type options supported by this realization technique."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariabilityRealizationConfiguration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variationPoint" lowerBound="1"
        eType="ecore:EClass ../../org.splevo.vpm/model/vpm.ecore#//variability/VariationPoint">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The configured variation point."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="technique" lowerBound="1"
        eType="#//VariabilityRealizationTechnique">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The realization technique selected for a variation point."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariabilityRealizationModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="RealizationConfigurations"
        upperBound="-1" eType="#//VariabilityRealizationConfiguration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vpm" lowerBound="1" eType="ecore:EClass ../../org.splevo.vpm/model/vpm.ecore#//variability/VariationPointModel"/>
  </eClassifiers>
</ecore:EPackage>
