<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="MoDiscoJavaVPM" nsURI="http://splevo.org/modisco/java/vpm/1.0"
    nsPrefix="org.splevo.modisco.java.vpm">
  <eSubpackages name="software" nsURI="http://splevo.org/modisco/java/vpm/1.0/software"
      nsPrefix="software">
    <eClassifiers xsi:type="ecore:EClass" name="MoDiscoJavaSoftwareElement" eSuperTypes="../../org.splevo.vpm/model/vpm.ecore#//software/JavaSoftwareElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A referencing object to the original MoDisco software element."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="astNode" lowerBound="1"
          eType="ecore:EClass platform:/plugin/org.eclipse.gmt.modisco.java/model/java.ecore#//ASTNode">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The MoDisco ASTNode representing the software element itself."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
