<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="java2kdmdiff" nsURI="http://www.eclipse.org/emf/compare/diff/java2kdmdiff/1.0"
    nsPrefix="java2kdmdiff">
  <eClassifiers xsi:type="ecore:EClass" name="Java2KDMDiffExtension" abstract="true"
      eSuperTypes="platform:/plugin/org.eclipse.emf.compare.diff/model/diff.ecore#//AbstractDiffExtension platform:/plugin/org.eclipse.emf.compare.diff/model/diff.ecore#//DiffElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An EMF Compare Diffing extension model specific for the java2kdm meta model extracted by the modisco tooling.&#xD;&#xA;&#xD;&#xA;This diffing uses the terms &quot;left model&quot; and &quot;right model&quot;. &#xD;&#xA;The right model identifies the original model.&#xD;&#xA;The left model the modified version."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StatementChange" eSuperTypes="#//Java2KDMDiffExtension">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A change on a statement level.&#xD;&#xA;Depending on the type of change (delete, add, remove, move) the left, right or both statement references are filled."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statementRight" eType="ecore:EClass platform:/plugin/org.eclipse.gmt.modisco.java/model/java.ecore#//Statement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The statement in the right model which is the new modified version."/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="statementRight"/>
        <details key="namespace" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statementLeft" eType="ecore:EClass platform:/plugin/org.eclipse.gmt.modisco.java/model/java.ecore#//Statement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The statement source element in the left model."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImportDeclarationChange" abstract="true"
      eSuperTypes="#//Java2KDMDiffExtension">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A difference identifying that an import has been changed."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="ImportDeclarationChange"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImportInsert" eSuperTypes="#//ImportDeclarationChange">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A change representing a new import which is only present in the right model."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="importLeft" eType="ecore:EClass platform:/plugin/org.eclipse.gmt.modisco.java/model/java.ecore#//ImportDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImportDelete" eSuperTypes="#//ImportDeclarationChange">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An import that was deleted and is only present in the right model."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="importRight" eType="ecore:EClass platform:/plugin/org.eclipse.gmt.modisco.java/model/java.ecore#//ImportDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftContainer" eType="ecore:EClass platform:/plugin/org.eclipse.gmt.modisco.java/model/java.ecore#//CompilationUnit">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The container in the chaned model that no longer contains the import. (according to emf compares &quot;leftParent&quot; terminology)"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassChange" abstract="true" eSuperTypes="#//Java2KDMDiffExtension"/>
  <eClassifiers xsi:type="ecore:EClass" name="ImplementsInterfaceInsert" eSuperTypes="#//ClassChange">
    <eStructuralFeatures xsi:type="ecore:EReference" name="implementedInterface" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.gmt.modisco.java/model/java.ecore#//InterfaceDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="changedClass" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.gmt.modisco.java/model/java.ecore#//ClassDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImplementsInterfaceDelete" eSuperTypes="#//ClassChange">
    <eStructuralFeatures xsi:type="ecore:EReference" name="implementedInterface" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.gmt.modisco.java/model/java.ecore#//InterfaceDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="changedClass" eType="ecore:EClass platform:/plugin/org.eclipse.gmt.modisco.java/model/java.ecore#//ClassDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FieldChange" abstract="true" eSuperTypes="#//Java2KDMDiffExtension"/>
  <eClassifiers xsi:type="ecore:EClass" name="FieldInsert" eSuperTypes="#//FieldChange">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fieldLeft" eType="ecore:EClass platform:/plugin/org.eclipse.gmt.modisco.java/model/java.ecore#//FieldDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FieldDelete" eSuperTypes="#//FieldChange">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fieldRight" eType="ecore:EClass platform:/plugin/org.eclipse.gmt.modisco.java/model/java.ecore#//FieldDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassInsert" eSuperTypes="#//ClassChange">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classLeft" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.gmt.modisco.java/model/java.ecore#//ClassDeclaration">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The added class declaration."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassDelete" eSuperTypes="#//ClassChange">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classRight" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.gmt.modisco.java/model/java.ecore#//ClassDeclaration">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The deleted class declaration."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftContainer" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.gmt.modisco.java/model/java.ecore#//Package">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The package in the current model that no longer contains the deleted class."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
