<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="java2kdmdiff" nsURI="http://www.eclipse.org/emf/compare/diff/java2kdmdiff/1.0"
    nsPrefix="java2kdmdiff">
  <eClassifiers xsi:type="ecore:EClass" name="Java2KDMDiffExtension" abstract="true"
      eSuperTypes="../../org.eclipse.emf.compare/model/compare.ecore#//Diff">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An EMF Compare Diffing extension model specific for the java2kdm meta model extracted by the modisco tooling.&#xD;&#xA;&#xD;&#xA;This diffing uses the terms &quot;left model&quot; and &quot;right model&quot;. &#xD;&#xA;The right model identifies the original model.&#xD;&#xA;The left model the modified version."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StatementChange" eSuperTypes="#//Java2KDMDiffExtension">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A change on a statement level.&#xD;&#xA;Depending on the type of change (delete, add, remove, move) the left, right or both statement references are filled."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="changedStatement" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.gmt.modisco.java/model/java.ecore#//Statement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImportChange" eSuperTypes="#//Java2KDMDiffExtension">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A difference identifying that an import has been changed."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="ImportDeclarationChange"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="changedImport" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.gmt.modisco.java/model/java.ecore#//ImportDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassChange" eSuperTypes="#//Java2KDMDiffExtension">
    <eStructuralFeatures xsi:type="ecore:EReference" name="changedClass" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.gmt.modisco.java/model/java.ecore#//ClassDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FieldChange" eSuperTypes="#//Java2KDMDiffExtension">
    <eStructuralFeatures xsi:type="ecore:EReference" name="changedField" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.gmt.modisco.java/model/java.ecore#//FieldDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PackageChange" eSuperTypes="#//Java2KDMDiffExtension">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A changed package declaration."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="changedPackage" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.gmt.modisco.java/model/java.ecore#//Package"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MethodChange" eSuperTypes="#//Java2KDMDiffExtension">
    <eStructuralFeatures xsi:type="ecore:EReference" name="changedMethod" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.gmt.modisco.java/model/java.ecore#//AbstractMethodDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumChange" eSuperTypes="#//Java2KDMDiffExtension">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Change that indications a modification of an enumeration type."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="changedEnum" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.gmt.modisco.java/model/java.ecore#//EnumDeclaration"/>
  </eClassifiers>
</ecore:EPackage>
